apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../upstream
# - generate-tls
# transformers:
# - generate-tls/statefulset_volume-patch-transformer.yaml
commonLabels:
  app.kubernetes.io/name: consul
  app.kubernetes.io/instance: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
replicas:
- name: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
  count: 1 # {"$ref":"#/definitions/io.k8s.cli.setters.replicas"}
configMapGenerator:
- name: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
  literals:
  - SERVICE_NAME=consul # {"$ref":"#/definitions/io.k8s.cli.substitutions.service-name"}
  - BOOTSTRAP_EXPECT=1 # {"$ref":"#/definitions/io.k8s.cli.substitutions.bootstrap-expect"}
  - CONSUL_HTTP_ADDR=http://127.0.0.1:8500
- name: consul-configs
  literals:
    - |-
        00-agent-defaults.hcl=
        verify_incoming = true
        verify_outgoing = true
        ca_file = "/consul/tls/consul-agent-ca.pem"
        ports = {
          http = -1
          https = 8500
        }
    - |-
        00-server-defaults.hcl=
        verify_server_hostname = true
        cert_file = "/consul/tls/server-consul.pem"
        key_file = "/consul/tls/server-consul-key.pem"
patches:
- path: generate-tls/statefulset_volume-patch.yaml
