apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
spec:
  serviceName: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: consul
        image: docker.io/library/consul:1.7.2
        command:
        - consul
        - agent
        - -advertise=$(POD_IP)
        - -bind=0.0.0.0
        - -bootstrap-expect=$(BOOTSTRAP_EXPECT)
        - -client=0.0.0.0
        - -config-dir=/consul/config
        - -data-dir=/consul/data
        - -ui
        - -retry-join=$(SERVICE_NAME).$(NAMESPACE).svc
        - -server
        envFrom:
        - configMapRef:
            name: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: consul-configs
          mountPath: /consul/config
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
        ports:
        - containerPort: 8500
          name: http
          protocol: "TCP"
        - containerPort: 8301
          name: serflan-tcp
          protocol: "TCP"
        - containerPort: 8301
          name: serflan-udp
          protocol: "UDP"
        - containerPort: 8302
          name: serfwan-tcp
          protocol: "TCP"
        - containerPort: 8302
          name: serfwan-udp
          protocol: "UDP"
        - containerPort: 8300
          name: server
          protocol: "TCP"
        - containerPort: 8600
          name: dns-tcp
          protocol: "TCP"
        - containerPort: 8600
          name: dns-udp
          protocol: "UDP"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - |
              curl \
                ${CONSUL_HTTP_ADDR}/v1/status/leader 2>/dev/null |\
                grep -E '".+"'
      volumes:
      - name: consul-data
        emptyDir: {}
      - name: consul-configs
        projected:
          sources:
            - configMap:
                name: consul-configs
