apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul # {"$ref":"#/definitions/io.k8s.cli.setters.instance"}
spec:
  template:
    spec:
      volumes:
      - name: consul-configs
        projected:
          sources:
            - configMap:
                name: consul-configs-tlss
